### ISSUE TITLE
Redis connection issue

### ISSUE THREAD

**Issue by kinouzero** [wizarrrrr/wizarr#21]
### The bug

Hi,

I just moved to your wizarr, so my previous configuration does not work anymore.
I tried to connect to my valkey (redis fork) but the backend container doesn't connect to it.

It seems it can't find the environment file, 2nd line of log

Did I miss something ?

### The OS that Wizarr is running on

Docker

### Version of Wizarr

3.5.6

### Platform with the issue

- [x] Server
- [ ] Web

### Your docker-compose.yml content

```YAML
  memcached:
    <<: [*basic, *network-zero, *restart-always]
    command:
        - --conn-limit=1024
        - --memory-limit=64
        - --threads=4
    container_name: ${MEMCACHED_NAME}
    image: memcached:${MEMCACHED_VERSION}
    healthcheck:
      <<: *healthcheck-basic
      test: echo stats | nc 127.0.0.1 11211

  valkey:
    <<: [*basic, *network-zero, *restart-always]
    container_name: ${VALKEY_NAME}
    image: valkey/valkey:${VALKEY_VERSION}
    labels:
      <<: *label-wud-semver
      wud.display.icon: 'sh-valkey'
      wud.display.name: 'Valkey'
      wud.link.template: 'https://hub.docker.com/r/valkey/valkey/tags'
    volumes:
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro

  wizarr:
    <<: [*basic, *network-zero, *restart-always]
    container_name: ${WIZARR_NAME}
    image: ghcr.io/wizarrrrr/wizarr-frontend:${LATEST_VERSION}
    labels:
      <<: *label-wud-semver-extra
      wud.display.icon: 'sh-wizarr'
      wud.display.name: 'Wizarr'
      wud.link.template: 'https://github.com/wizarrrrr/wizarr/pkgs/container/wizarr-frontend'

  wizarr-api:
    <<: [*basic, *network-zero, *restart-always]
    container_name: ${WIZARR_API_NAME}
    depends_on:
      - ${WIZARR_DB_NAME}
      - ${VALKEY_NAME}
    environment:
      DB_HOSTNAME: ${WIZARR_DB_NAME}
      DB_PASSWORD_FILE: ${POSTGRES_FILE_PASSWORD}
      DB_USERNAME: ${USER}
      REDIS_HOSTNAME: ${VALKEY_NAME}
      TZ: ${TZ}
      WIZARR_LOG_LEVEL: ${LOG_LEVEL}
    healthcheck:
      <<: *healthcheck-basic
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
    image: ghcr.io/wizarrrrr/wizarr-backend:${LATEST_VERSION}
    labels:
      <<: *label-wud-semver-extra
      wud.display.icon: 'sh-wizarr'
      wud.display.name: 'Wizarr API'
      wud.link.template: 'https://github.com/wizarrrrr/wizarr/pkgs/container/wizarr-backend'
    secrets:
      - POSTGRES_PASSWORD
    volumes:
      - type: volume
        source: wizarr_data
        target: /usr/wizarr/data/storage
        volume:
          nocopy: true
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro

  wizarr-db:
    <<: [*basic, *network-zero, *restart-always]
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    container_name: ${WIZARR_DB_NAME}
    environment:
      POSTGRES_DB: ${WIZARR_NAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${USER}
    image: tensorchord/pgvecto-rs:${POSTGRES_VECTOR_VERSION}
    labels:
      wud.watch: false
      wud.display.icon: 'sh-wizarr'
      wud.display.name: 'Wizarr DB'
    ports:
      - 5434:${POSTGRES_PORT}
    volumes:
      - type: volume
        source: wizarr_db
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - ${DIR_LOCALTIME}:${DIR_LOCALTIME}:ro
```

### Your .env content

```Shell
# Valkey
VALKEY_NAME='valkey'
VALKEY_PORT='6379'

# Wizarr
WIZARR_NAME='wizarr'
WIZARR_API_NAME='wizarr-api'
WIZARR_DB_NAME='wizarr-db'
```

### Reproduction steps

Just run the compose file

### Relevant log output

```shell
Running Wizarr Backend in production mode
 WARN  Environment file not found. Using default environment variables.
Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1615:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',

  port: 6379
}
 ┌─────── Failed to connect to Redis ──────────┐
 │                                             │
 │  Failed to connect to Redis at:             │
 │  localhost:6379                             │
 │                                             │
 │  Please check the connection and try again  │
 │                                             │
 └─────────────────────────────────────────────┘
```
