### ISSUE TITLE
latest backend image does not reflect current latest release and doesn't start because of private.key issue

### ISSUE THREAD

**Issue by appiekap653** [wizarrrrr/wizarr#22]
### The bug

The backend container keeps looping with this error:

```
Node.js v22.12.0

Running Wizarr Backend in production mode

 WARN  Environment file not found. Using default environment variables.

node:fs:2344

    return binding.writeFileUtf8(

                   ^

Error: ENOENT: no such file or directory, open '/home/user/docker/data/wizarrorig/storage/private.key'

    at writeFileSync (node:fs:2344:20)

    at RsaKeyPairGenJob.<anonymous> (/usr/wizarr/apps/server/src/utils/secret.helper.js:38:36)

    at job.ondone (node:internal/crypto/keygen:93:5) {

  errno: -2,

  code: 'ENOENT',

  syscall: 'open',

  path: '/home/user/docker/data/wizarrorig/storage/private.key'

}

```

### The OS that Wizarr is running on

Docker

### Version of Wizarr

3.5.6

### Platform with the issue

- [x] Server
- [ ] Web

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/wizarrrrr/wizarr/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

name: wizarr_orig

secrets:
  wizarr_postgresql_password:
    file: /home/user/docker/secrets/wizarr_postgresql_password

services:
    # wizarr-nginx:
    #     restart: on-failure
    #     image: nginx:1.24.0-alpine
    #     depends_on:
    #         wizarr-frontend:
    #             condition: service_started
    #         wizarr-backend:
    #             condition: service_started
    #     ports:
    #         - ${PORT:-5690}:5690
    #     environment:
    #         - PORT=5690
    #         - FRONT_URL=http://wizarr-frontend:5173
    #         - SERVER_URL=http://wizarr-backend:5001
    #     volumes:
    #         - ./nginx.conf.template:/etc/nginx/templates/wizarr.conf.template:ro

  wizarr-frontend:
    container_name: wizarr-frontend
    hostname: wizarr-frontend
    image: ghcr.io/wizarrrrr/wizarr-frontend:${WIZARR_IMAGE_VERSION:-latest}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 5173
    networks:
      - external
      - wizarr-orig-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wizzarr-orig-front-rtr.rule=Host(`wizzarrorig.my.com`) && !PathPrefix(`/api`) && !PathPrefix(`/admin/bull`) && !PathPrefix(`/socket.io`)"
      - "traefik.http.routers.wizzarr-orig-front-rtr.priority=2"
      - "traefik.http.routers.wizzarr-orig-front-rtr.entrypoints=websecure"
      - "traefik.http.routers.wizzarr-orig-front-rtr.tls=true"
      - "traefik.http.routers.wizzarr-orig-front-rtr.service=wizzarr-orig-front-svc"
      - "traefik.http.routers.wizzarr-orig-front-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      - "traefik.http.services.wizzarr-orig-front-svc.loadBalancer.server.port=5173"

  wizarr-backend:
    container_name: wizarr-backend
    hostname: wizarr-backend
    image: ghcr.io/wizarrrrr/wizarr-backend:${WIZARR_IMAGE_VERSION:-latest}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    depends_on:
      - wizarr-redis
      - wizarr-postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      # Do not edit the next line. If you want to change the storage location on your system, edit the value of STORAGE_DIR in the .env file
      - ${DB_DIR}:/usr/wizarr/data/database:rw
      - ${STORAGE_DIR}:/usr/wizarr/data/storage:rw
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    expose:
      - 5001
    networks:
      - external
      - wizarr-orig-internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wizzarr-orig-back-rtr.rule=Host(`wizarrorig.my.com`) && PathPrefix(`/api`) || Host(`wizarrorig.my.com`) && PathPrefix(`/admin/bull`) || Host(`wizarrorig.my.com`) && PathPrefix(`/socket.io`)"
      - "traefik.http.routers.wizzarr-orig-back-rtr.priority=1"
      - "traefik.http.routers.wizzarr-orig-back-rtr.entrypoints=websecure"
      - "traefik.http.routers.wizzarr-orig-back-rtr.tls=true"
      - "traefik.http.routers.wizzarr-orig-back-rtr.service=wizzarr-orig-back-svc"
      - "traefik.http.routers.wizzarr-orig-back-rtr.middlewares=chain-no-auth-no-crowdsec@file"
      - "traefik.http.services.wizzarr-orig-back-svc.loadBalancer.server.port=5001"

  wizarr-redis:
    container_name: wizarr-redis
    hostname: wizarr-redis
    image: docker.io/redis:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
    expose:
      - 6379
    networks:
      - wizarr-orig-internal

  wizarr-postgres:
    container_name: wizarr-postgres
    hostname: wizarr-postgres
    image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    secrets:
      - wizarr_postgresql_password
    command: >-
      postgres
      -c shared_preload_libraries=vectors.so
      -c 'search_path="$$user", public, vectors'
      -c logging_collector=on
      -c max_wal_size=2GB
      -c shared_buffers=512MB
      -c wal_compression=on
    volumes:
      # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DIR in the .env file
      - ${DB_DIR}:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD_FILE: ${DB_PASSWORD_FILE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DIR}
      POSTGRES_INITDB_ARGS: "--data-checksums"
    networks:
      - wizarr-orig-internal

  wizarr-memcached:
    container_name: wizarr-memcached
    hostname: wizarr-memcached
    image: "memcached:alpine"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    healthcheck:
      test: echo stats | nc 127.0.0.1 11211
      interval: 20s
      timeout: 1s
      retries: 5
    expose:
      - 11211
    networks:
      - wizarr-orig-internal

  wizarr-s3:
    container_name: wizarr-s3
    hostname: wizarr-s3
    image: zenko/cloudserver:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - ${STORAGE_DIR}/meta:/var/lib/s3/meta:rw
      - ${STORAGE_DIR}/data:/var/lib/s3/data:rw
    environment:
      S3METADATAPATH: /var/lib/s3/meta
      S3DATAPATH: /var/lib/s3/data
      REMOTE_MANAGEMENT_DISABLE: true
      HOST_NAMES: "s3"
    networks:
      - wizarr-orig-internal

########################### NETWORKS
networks:
  external:
    external: true

  wizarr-orig-internal:
    name: wizarr-orig-internal
    driver: bridge
    internal: true
    enable_ipv6: false
    ipam:
      config:
        - subnet: 172.32.4.0/24
          gateway: 172.32.4.1
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://wizarr.org/install/environment-variables

# The location where Wizarr will store files
STORAGE_DIR=/home/user/docker/data/wizarrorig/storage
# The location where your database files are stored
DB_DIR=/home/user/docker/data/wizarrorig/database

# The type of database to use for Wizarr, can be either postgres or sqlite
DB_TYPE=postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_DB_time_zones#List
TZ=Europe/Amsterdam

# The Wizarr version to use. You can pin this to a specific version like "v1.71.0"
WIZARR_IMAGE_VERSION=3.5.6


WIZARR_TRUSTED_PROXIES=172.30.0.254
WIZARR_PROCESS_INVALID_IMAGES=true
WIZARR_LOG_LEVEL=log
#WIZARR_ENV=production

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD_FILE=/run/secrets/wizarr_postgresql_password
# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_HOST=wizarr-postgres
DB_NAME=wizarr

REDIS_HOST=wizarr-redis
REDIS_PORT=6379

MEMCACHED_HOST=wizarr-memcached
MEMCACHED_PORT=11211
```

### Reproduction steps

1. start the containers
...

### Relevant log output

```shell

```
