### ISSUE TITLE
Error Creating Jellyfin Server

### ISSUE THREAD

**Issue by Panda260** [wizarrrrr/wizarr#23]
### The bug

tested with both domains and local ips
![Image](https://github.com/user-attachments/assets/5db005cf-6f18-4b6e-bcd8-8211a259859b)

### The OS that Wizarr is running on

Docker

### Version of Wizarr

v3.5.6

### Platform with the issue

- [x] Server
- [ ] Web

### Your docker-compose.yml content

```YAML
#
# WARNING: Make sure to use the docker-compose.yml of the current release:
#
# https://github.com/wizarrrrr/wizarr/releases/latest/download/docker-compose.yml
#
# The compose file on main may not be compatible with the latest release.
#

services:
    wizarr-nginx:
        restart: on-failure
        image: nginx:1.24.0-alpine
        depends_on:
            wizarr-frontend:
                condition: service_started
            wizarr-backend:
                condition: service_started
        ports:
            - ${PORT:-5690}:5690
        environment:
            - PORT=5690
            - FRONT_URL=http://wizarr-frontend:5173
            - SERVER_URL=http://wizarr-backend:5001
        volumes:
            - ./nginx.conf.template:/etc/nginx/templates/wizarr.conf.template:ro

    wizarr-frontend:
        container_name: wizarr_frontend
        image: ghcr.io/wizarrrrr/wizarr-frontend:${WIZARR_IMAGE_VERSION:-latest}
        restart: always

    wizarr-backend:
        container_name: wizarr_backend
        image: ghcr.io/wizarrrrr/wizarr-backend:${WIZARR_IMAGE_VERSION:-latest}
        user: 0:0
        volumes:
            # Do not edit the next line. If you want to change the storage location on your system, edit the value of STORAGE_DIR in the .env file
            - ${DB_DIR}:/usr/wizarr/data/database
            - ${STORAGE_DIR}:/usr/wizarr/data/storage
            - /etc/localtime:/etc/localtime:ro
        env_file:
            - .env
        depends_on:
            - redis
            - postgres
        restart: always
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
            interval: 30s
            timeout: 10s
            retries: 5

    redis:
        container_name: wizarr_redis
        image: docker.io/redis:latest
        healthcheck:
            test: redis-cli ping || exit 1
        restart: always

    postgres:
        container_name: wizarr_postgres
        image: docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DIR}
            POSTGRES_INITDB_ARGS: "--data-checksums"
        volumes:
            # Do not edit the next line. If you want to change the database storage location on your system, edit the value of DB_DIR in the .env file
            - ${DB_DIR}:/var/lib/postgresql/data
        command: >-
            postgres
            -c shared_preload_libraries=vectors.so
            -c 'search_path="$$user", public, vectors'
            -c logging_collector=on
            -c max_wal_size=2GB
            -c shared_buffers=512MB
            -c wal_compression=on
        restart: always

    memcached:
        container_name: wizarr_memcached
        restart: always
        image: "memcached:alpine"
        command:
            - --conn-limit=1024
            - --memory-limit=64
            - --threads=4
        healthcheck:
            test: echo stats | nc 127.0.0.1 11211
            interval: 20s
            timeout: 1s
            retries: 5

    s3:
        container_name: wizarr_s3
        restart: always
        image: zenko/cloudserver:latest
        environment:
            S3METADATAPATH: /var/lib/s3/meta
            S3DATAPATH: /var/lib/s3/data
            REMOTE_MANAGEMENT_DISABLE: 1
            HOST_NAMES: "s3"
        volumes:
            - ${STORAGE_DIR}/meta:/var/lib/s3/meta
            - ${STORAGE_DIR}/data:/var/lib/s3/data
```

### Your .env content

```Shell
# You can find documentation for all the supported env variables at https://wizarr.org/install/environment-variables

# The location where Wizarr will store files
STORAGE_DIR=./data/storage
# The location where your database files are stored
DB_DIR=./data/database

# The type of database to use for Wizarr, can be either postgres or sqlite
DB_TYPE=postgres

# To set a timezone, uncomment the next line and change Etc/UTC to a TZ identifier from this list: https://en.wikipedia.org/wiki/List_of_tz_DB_time_zones#List
# TZ=Etc/UTC

# The Wizarr version to use. You can pin this to a specific version like "v1.71.0"
WIZARR_IMAGE_VERSION=latest

# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
DB_PASSWORD=

# The values below this line do not need to be changed
###################################################################################
DB_USERNAME=postgres
DB_HOST=wizarr_postgres
DB_NAME=wizarr

REDIS_HOST=redis
REDIS_PORT=6379

MEMCACHED_HOST=memcached
MEMCACHED_PORT=11211
```

### Reproduction steps

1. follow setup
2. try creating jellyfin server
3. enter ips
4. see error

### Relevant log output

```shell
Fetched result for latest_stable: v3.5.6
Fetched result for current_version: v3.5.6
ℹ Creating a new server

 ERROR  Server could not be verified

    at new HttpError (node_modules/routing-controllers/cjs/http-error/HttpError.js:17:22)
    at new BadRequestError (node_modules/routing-controllers/cjs/http-error/BadRequestError.js:10:9)
    at new InvalidServer (apps/server/src/api/exceptions/InvalidServer.js:7:9)
    at ServerService.create (apps/server/src/api/services/Server/ServerService.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async descriptor.value (apps/server/src/decorators/StripApiKeyDecorator.js:12:28)
    at async apps/server/src/middlewares/router/Application/SentryMiddleware.js:25:21

Fetched result for current_version: v3.5.6
Fetched result for current_version: v3.5.6
Fetched result for current_version: v3.5.6
Fetched result for current_version: v3.5.6
Fetched result for latest_stable: v3.5.6

 ERROR  Missing refresh token

    at new HttpError (node_modules/routing-controllers/cjs/http-error/HttpError.js:17:22)
    at new UnauthorizedError (node_modules/routing-controllers/cjs/http-error/UnauthorizedError.js:10:9)
    at new InvalidCredentials (apps/server/src/api/exceptions/InvalidCredentials.js:7:9)
    at LoginService.refresh (apps/server/src/api/services/Authentication/LoginService.js:76:19)
    at LoginController.refresh (apps/server/src/api/controllers/router/Authentication/LoginController.js:40:34)
    at ActionMetadata.callMethod (node_modules/routing-controllers/cjs/metadata/ActionMetadata.js:91:48)
    at node_modules/routing-controllers/cjs/RoutingControllers.js:96:34
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async apps/server/src/middlewares/router/Application/SentryMiddleware.js:25:21

ℹ Creating a new server

 ERROR  Server could not be verified

    at new HttpError (node_modules/routing-controllers/cjs/http-error/HttpError.js:17:22)
    at new BadRequestError (node_modules/routing-controllers/cjs/http-error/BadRequestError.js:10:9)
    at new InvalidServer (apps/server/src/api/exceptions/InvalidServer.js:7:9)
    at ServerService.create (apps/server/src/api/services/Server/ServerService.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async descriptor.value (apps/server/src/decorators/StripApiKeyDecorator.js:12:28)
    at async apps/server/src/middlewares/router/Application/SentryMiddleware.js:25:21

ℹ Creating a new server

 ERROR  Server could not be verified

    at new HttpError (node_modules/routing-controllers/cjs/http-error/HttpError.js:17:22)
    at new BadRequestError (node_modules/routing-controllers/cjs/http-error/BadRequestError.js:10:9)
    at new InvalidServer (apps/server/src/api/exceptions/InvalidServer.js:7:9)
    at ServerService.create (apps/server/src/api/services/Server/ServerService.js:62:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async descriptor.value (apps/server/src/decorators/StripApiKeyDecorator.js:12:28)
    at async apps/server/src/middlewares/router/Application/SentryMiddleware.js:25:21
```
